# Generated by Django 5.0.1 on 2024-01-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('Max_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Card_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('Value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Rule',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Until', models.IntegerField()),
                ('Value', models.FloatField()),
                ('Contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudPark.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Plan',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Due_date', models.DateTimeField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudPark.customer')),
                ('Plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudPark.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Plate', models.CharField(max_length=10)),
                ('Model', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudPark.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Parkmovement',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Entry_date', models.DateTimeField()),
                ('Exit_date', models.DateTimeField()),
                ('Value', models.FloatField()),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudPark.vehicle')),
            ],
        ),
    ]
